apiVersion: v1
kind: Service
metadata:
  name: meteo-service
spec:
  selector:
    app: meteo
    module: station-simulator
  type: ClusterIP #Inutile car c'est le type par défaut
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080