apiVersion: v1
kind: Pod
metadata:
  name: data-editor
  labels:
    app: my-app-data-editor
spec:
  containers:
    - name: mycontainer-with-pvc
      image: amouat/network-utils
      ports:
        - containerPort: 8080
          name : mon-port-http
      command: ['sh', '-c', 'trap : TERM INT; sleep infinity & wait']
      volumeMounts:
        - name: my-volume-data-editor
          mountPath: "/data"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - all
          #add: ["..."]
  volumes:
    - name: my-volume-data-editor
      persistentVolumeClaim:
        claimName: static-web-site