apiVersion: v1
data:
  my-conf-nginx.conf: "server {\r\n        listen 80;\r\n        location / {\r\n
    \           proxy_pass http://final-tp-service-station-simulator;\r\n        }\r\n
    \   }"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: my-configmap-final-tp
