apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-tp-deploy-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      module: backend
  template:
    metadata:
      labels:
        module: backend
    spec:
      containers:
        - name: my-postgres
          image: postgres:12.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: port-postgre
          volumeMounts:
            - name: my-volume-final-tp
              mountPath: "/data"
            - name: secret-volume-final-tp
              readOnly: true
              mountPath: "/etc/secret-volume"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-postgre-user
                  key: my-secret-final-tp
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgre-pwd
                  key: my-secret-final-tp
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-postgre-db
                  key: my-secret-final-tp
      volumes:
        - name: secret-volume-final-tp
          secret:
            secretName: my-secret-final-tp
            defaultMode: 256
        - name: my-volume-final-tp
          persistentVolumeClaim:
            claimName: my-volume-final-tp

---

apiVersion: v1
kind: Service
metadata:
  name: final-tp-service-station-simulator
spec:
  selector:
    module: my-module-station-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: port-postgre