apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: amouat/network-utils
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name : mon-port-http
      command: ['sh', '-c', 'trap : TERM INT; sleep infinity & wait']
      env:
       - name: my-key
         valueFrom:
          configMapKeyRef:
           name: my-configmap
           key: my-key
      envFrom:
        - configMapRef:
            name : my-configmap-2
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - all
          #add: ["..."]