apiVersion: v1
kind: Pod
metadata:
  name: my-pod-network-utils
  labels:
    app: my-app-network-utils
    #module: station-simulator
spec:
  containers:
    - name: mycontainer
      image: amouat/network-utils
      ports:
        - containerPort: 8080
          name : mon-port-http
      command: ['sh', '-c', 'trap : TERM INT; sleep infinity & wait']
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
        defaultMode: 256