apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: meteo
    module: station-simulator
spec:
  containers:
    - name: my-app
      image: eu.gcr.io/formation-k8s-247908/station-simulator:latest
      ports:
        - containerPort: 8080