apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
    #module: station-simulator
spec:
  containers:
    - name: my-app
      image: amouat/network-utils
      ports:
        - containerPort: 8080
          name : mon-port-http
      command: ['sh', '-c', 'trap : TERM INT; sleep infinity & wait']
      env:
       - name: my-key
         valueFrom:
          configMapKeyRef:
           name: my-configmap
           key: my-key
      envFrom:
        - configMapRef:
            name : my-configmap-2