apiVersion: v1
kind: Pod
metadata:
  name: my-pod-for-configmap-2
  labels:
    app: my-app-for-configmap-2
spec:
  containers:
    - name: my-app-for-configmap-2
      image: nginx:1.17.4
      imagePullPolicy: Always
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - all
          #add: ["..."]
  volumes:
    - name: config-volume
      configMap:
        name: my-conf